name: Daily Math Problem
on:
  schedule:
    - cron: '0 0 * * *'  # Run at midnight UTC
  workflow_dispatch:      # Allow manual triggers
    inputs:
      date:
        description: 'Date for the problem (YYYY-MM-DD)'
        required: false
        type: string

jobs:
  select-problem:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This allows writing to repository contents (commits)
    timeout-minutes: 15  # Add timeout to prevent hanging jobs
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: problem-of-day/node_modules
          key: ${{ runner.os }}-problem-of-day-${{ hashFiles('problem-of-day/package.json') }}
          restore-keys: |
            ${{ runner.os }}-problem-of-day-
          
      - name: Install dependencies for problem-of-day
        working-directory: problem-of-day
        run: npm ci
        
      - name: Select and publish problem
        if: ${{ !github.event.inputs.date }}
        run: node problem-of-day/js/select-problem.js
        
      - name: Select and publish problem for specific date
        if: ${{ github.event.inputs.date }}
        run: node problem-of-day/js/select-problem.js ${{ github.event.inputs.date }}
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add problem of the day for ${{ github.event.inputs.date || format('$(date +%Y-%m-%d)') }}"
          file_pattern: 'problem-of-day/published-problems.json problem-of-day/assets/*'